### ISSUE TITLE
[Feature Request] Manjaro (arch linux) support.

### ISSUE THREAD

**Issue by taitep** [modular/mojo#1035] opened 2023-10-10 13:30 UTC
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I think that adding support for more linux distros to mojo sdk should be prioritized, as i do not think it could be that complicated, and it would be very useful. I am myself a user of manjaro linux (an arch based distro), and beleive targeting arch next is a good idea, as after debian (because of ubuntu), most people probably use somthing based on arch (or arch itself).

### What is your motivation for this change?

It would not be too complicated (i think) and a very important thing for mojo. I think some sort of support should be prioritized over many other things. If you want to improve the language, you need feedback. To get feedback, you need people to give feedback. Not having the SDK without a vm, will make people not use mojo, resulting in maybe forgetting it.

### Any other details?

It should work for all arch based distros that do not change a lot that has to do with this. Therefore, you should not test specifically for some arch based distros in the installer, and instead try the arch method. Distros you know do not work or work differently can be checked for then.

**Comment by ematejska** [comment] 2023-10-10 16:29
I believe this is a duplicate of https://github.com/modularml/mojo/issues/572.  Please upvote that ticket.

**Closed as completed by ematejska** 2023-10-10 16:29 UTC
Labels: enhancement, mojo, mojo-repo
