### ISSUE TITLE
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):

### ISSUE THREAD

**Issue by bsmsultani** [modular/mojo#1417] opened 2023-12-06 13:01 UTC
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo main.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo                     0x00000001020f3764 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  mojo                     0x00000001020f18c4 llvm::sys::RunSignalHandlers() + 112
2  mojo                     0x00000001020f3e00 SignalHandler(int) + 344
3  libsystem_platform.dylib 0x00000001807d1a24 _sigtramp + 56
4  libsystem_platform.dylib 0x000000028001cb54 _sigtramp + 4286886248
5  libsystem_platform.dylib 0x00000002800295f4 _sigtramp + 4286938120
6  mojo                     0x00000001024b8cf8 M::KGEN::ExecutionEngine::runProgram(llvm::StringRef, llvm::StringRef, llvm::function_ref<M::ErrorOrSuccess (void*)>) + 212
7  mojo                     0x000000010204d0bc run(M::State const&) + 3872
8  mojo                     0x0000000102036f5c main + 1648
9  dyld                     0x0000000180429058 start + 2224
[15572:590639:20231206,230009.227834:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)

**Comment by ematejska** [comment] 2024-01-09 00:30
Closing this because there are no steps to reproduce the crash.  Thank you for submitting but we also need steps to reproduce.

**Closed as completed by ematejska** 2024-01-09 00:30 UTC
Labels: mojo, mojo-repo
