### ISSUE TITLE
[Modular CLI]: unable to install with Python 3.12

### ISSUE THREAD

**Issue by SimbaNinja917** [modular/mojo#1365] opened 2023-12-04 00:04 UTC
### Issue description

Hello, I am getting this error when I try to install Mojo `modular install mojo` I get the error: 

```
ModuleNotFoundError: No module named 'imp'
modular: error: failed to run python:
```

### Complete Terminal Log 
```
❯ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.5.1
# Installing to /Users/macbook/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0 (from -r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1))
  Using cached find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting papermill==2.4.0 (from -r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Using cached papermill-2.4.0-py3-none-any.whl (38 kB)
Collecting jupyter_client>=8.3.0 (from -r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for jupyter_client>=8.3.0 from https://files.pythonhosted.org/packages/43/ae/5f4f72980765e2e5e02b260f9c53bcc706cefa7ac9c8d7240225c55788d4/jupyter_client-8.6.0-py3-none-any.whl.metadata
  Using cached jupyter_client-8.6.0-py3-none-any.whl.metadata (8.3 kB)
Collecting ipykernel>=6.25.0 (from -r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for ipykernel>=6.25.0 from https://files.pythonhosted.org/packages/73/14/ec9a1c42d2c952c848a1ac366718783ab725148faf910bc086601809cefd/ipykernel-6.27.1-py3-none-any.whl.metadata
  Using cached ipykernel-6.27.1-py3-none-any.whl.metadata (6.3 kB)
Collecting ansiwrap (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Using cached ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting click (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for click from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting pyyaml (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for pyyaml from https://files.pythonhosted.org/packages/84/02/404de95ced348b73dd84f70e15a41843d817ff8c1744516bf78358f2ffd2/PyYAML-6.0.1-cp312-cp312-macosx_11_0_arm64.whl.metadata
  Using cached PyYAML-6.0.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting nbformat>=5.1.2 (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for nbformat>=5.1.2 from https://files.pythonhosted.org/packages/f4/e7/ef30a90b70eba39e675689b9eaaa92530a71d7435ab8f9cae520814e0caf/nbformat-5.9.2-py3-none-any.whl.metadata
  Using cached nbformat-5.9.2-py3-none-any.whl.metadata (3.4 kB)
Collecting nbclient>=0.2.0 (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for nbclient>=0.2.0 from https://files.pythonhosted.org/packages/6b/3a/607149974149f847125c38a62b9ea2b8267eb74823bbf8d8c54ae0212a00/nbclient-0.9.0-py3-none-any.whl.metadata
  Using cached nbclient-0.9.0-py3-none-any.whl.metadata (7.8 kB)
Collecting tqdm>=4.32.2 (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for tqdm>=4.32.2 from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting requests (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting entrypoints (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting tenacity (from papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for tenacity from https://files.pythonhosted.org/packages/f4/f1/990741d5bb2487d529d20a433210ffa136a367751e454214013b441c4575/tenacity-8.2.3-py3-none-any.whl.metadata
  Using cached tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from jupyter_client>=8.3.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for jupyter-core!=5.0.*,>=4.12 from https://files.pythonhosted.org/packages/ab/ea/af6508f71d2bcbf4db538940120cc3d3f10287f62105e756bd315aa345b5/jupyter_core-5.5.0-py3-none-any.whl.metadata
  Using cached jupyter_core-5.5.0-py3-none-any.whl.metadata (3.4 kB)
Collecting python-dateutil>=2.8.2 (from jupyter_client>=8.3.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyzmq>=23.0 (from jupyter_client>=8.3.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for pyzmq>=23.0 from https://files.pythonhosted.org/packages/d6/2a/812e25ea9fe6eeb18aed211e1dcd2fb6836fd79a848f4ad8cee8e11f839c/pyzmq-25.1.1-cp312-cp312-macosx_10_15_universal2.whl.metadata
  Using cached pyzmq-25.1.1-cp312-cp312-macosx_10_15_universal2.whl.metadata (4.9 kB)
Collecting tornado>=6.2 (from jupyter_client>=8.3.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for tornado>=6.2 from https://files.pythonhosted.org/packages/4a/2e/3ba930e3af171847d610e07ae878e04fcb7e4d7822f1a2d29a27b128ea24/tornado-6.4-cp38-abi3-macosx_10_9_universal2.whl.metadata
  Using cached tornado-6.4-cp38-abi3-macosx_10_9_universal2.whl.metadata (2.5 kB)
Collecting traitlets>=5.3 (from jupyter_client>=8.3.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for traitlets>=5.3 from https://files.pythonhosted.org/packages/a7/1d/7d07e1b152b419a8a9c7f812eeefd408a0610d869489ee2e86973486713f/traitlets-5.14.0-py3-none-any.whl.metadata
  Using cached traitlets-5.14.0-py3-none-any.whl.metadata (10 kB)
Collecting appnope (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Using cached appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
Collecting comm>=0.1.1 (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for comm>=0.1.1 from https://files.pythonhosted.org/packages/7b/a6/5fd0242e974914b139451eea0a61ed9fd2e47157e33a67939043c50a94dd/comm-0.2.0-py3-none-any.whl.metadata
  Using cached comm-0.2.0-py3-none-any.whl.metadata (3.7 kB)
Collecting debugpy>=1.6.5 (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for debugpy>=1.6.5 from https://files.pythonhosted.org/packages/64/59/b9c5dbe60c3a3e4e4bb12b1968aa75e98b99ff8b65273a5e7de75cceef75/debugpy-1.8.0-py2.py3-none-any.whl.metadata
  Using cached debugpy-1.8.0-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting ipython>=7.23.1 (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for ipython>=7.23.1 from https://files.pythonhosted.org/packages/47/6b/d9fdcdef2eb6a23f391251fde8781c38d42acd82abe84d054cb74f7863b0/ipython-8.18.1-py3-none-any.whl.metadata
  Using cached ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
Collecting matplotlib-inline>=0.1 (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting nest-asyncio (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for nest-asyncio from https://files.pythonhosted.org/packages/ab/d3/48c01d1944e0ee49fdc005bf518a68b0582d3bd201e5401664890b62a647/nest_asyncio-1.5.8-py3-none-any.whl.metadata
  Using cached nest_asyncio-1.5.8-py3-none-any.whl.metadata (2.8 kB)
Collecting packaging (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for packaging from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting psutil (from ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for psutil from https://files.pythonhosted.org/packages/9e/cb/e4b83c27eea66bc255effc967053f6fce7c14906dd9b43a348ead9f0cfea/psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl.metadata
  Using cached psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl.metadata (21 kB)
Collecting decorator (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for jedi>=0.16 from https://files.pythonhosted.org/packages/20/9f/bc63f0f0737ad7a60800bfd472a4836661adae21f9c2535f3957b1e54ceb/jedi-0.19.1-py2.py3-none-any.whl.metadata
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting prompt-toolkit<3.1.0,>=3.0.41 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for prompt-toolkit<3.1.0,>=3.0.41 from https://files.pythonhosted.org/packages/1f/9d/be9b01085bbd67a71c4b6aa02518fade8104e7a2224e5de5e947811d7176/prompt_toolkit-3.0.41-py3-none-any.whl.metadata
  Using cached prompt_toolkit-3.0.41-py3-none-any.whl.metadata (6.5 kB)
Collecting pygments>=2.4.0 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for pygments>=2.4.0 from https://files.pythonhosted.org/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl.metadata
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting stack-data (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for stack-data from https://files.pythonhosted.org/packages/f1/7b/ce1eafaf1a76852e2ec9b22edecf1daa58175c090266e9f6c64afcd81d91/stack_data-0.6.3-py3-none-any.whl.metadata
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting pexpect>4.3 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for pexpect>4.3 from https://files.pythonhosted.org/packages/9e/c3/059298687310d527a58bb01f3b1965787ee3b40dce76752eda8b44e9a2c5/pexpect-4.9.0-py2.py3-none-any.whl.metadata
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for platformdirs>=2.5 from https://files.pythonhosted.org/packages/31/16/70be3b725073035aa5fc3229321d06e22e73e3e09f6af78dcfdf16c7636c/platformdirs-4.0.0-py3-none-any.whl.metadata
  Using cached platformdirs-4.0.0-py3-none-any.whl.metadata (11 kB)
Collecting fastjsonschema (from nbformat>=5.1.2->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for fastjsonschema from https://files.pythonhosted.org/packages/63/e9/d3dca06ea6b8e58e65716973bc7d9bee9bc39ce233595aa04d04e89a1089/fastjsonschema-2.19.0-py3-none-any.whl.metadata
  Using cached fastjsonschema-2.19.0-py3-none-any.whl.metadata (2.0 kB)
Collecting jsonschema>=2.6 (from nbformat>=5.1.2->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for jsonschema>=2.6 from https://files.pythonhosted.org/packages/0f/ed/0058234d8dd2b1fc6beeea8eab945191a05e9d391a63202f49fe23327586/jsonschema-4.20.0-py3-none-any.whl.metadata
  Using cached jsonschema-4.20.0-py3-none-any.whl.metadata (8.1 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting textwrap3>=0.9.2 (from ansiwrap->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Using cached textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Collecting charset-normalizer<4,>=2 (from requests->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/3a/52/9f9d17c3b54dc238de384c4cb5a2ef0e27985b42a0e5cc8e8a31d918d48d/charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl.metadata
  Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for idna<4,>=2.5 from https://files.pythonhosted.org/packages/c2/e7/a82b05cf63a603df6e68d59ae6a68bf5064484a0718ea5033660af4b54a9/idna-3.6-py3-none-any.whl.metadata
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/96/94/c31f58c7a7f470d5665935262ebd7455c7e4c7782eb525658d3dbf4b9403/urllib3-2.1.0-py3-none-any.whl.metadata
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe4f42/certifi-2023.11.17-py3-none-any.whl.metadata
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for jsonschema-specifications>=2023.03.6 from https://files.pythonhosted.org/packages/d7/48/b62ccba8f4ac91817d6a11b340e63806175dafb10234a8cf7140bd389da5/jsonschema_specifications-2023.11.2-py3-none-any.whl.metadata
  Using cached jsonschema_specifications-2023.11.2-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for referencing>=0.28.4 from https://files.pythonhosted.org/packages/ec/d8/e826b3f743d97e45d3ace674a5c6f026069428e608c5fde3d08d072c87f2/referencing-0.31.1-py3-none-any.whl.metadata
  Using cached referencing-0.31.1-py3-none-any.whl.metadata (2.7 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for rpds-py>=0.7.1 from https://files.pythonhosted.org/packages/22/5b/1f4324d19582e2a745d58fd975bd35ac1d7dd561dc25a0cad2edaa088b34/rpds_py-0.13.2-cp312-cp312-macosx_11_0_arm64.whl.metadata
  Using cached rpds_py-0.13.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (3.9 kB)
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for wcwidth from https://files.pythonhosted.org/packages/31/b1/a59de0ad3aabb17523a39804f4c6df3ae87ead053a4e25362ae03d73d03a/wcwidth-0.2.12-py2.py3-none-any.whl.metadata
  Using cached wcwidth-0.2.12-py2.py3-none-any.whl.metadata (14 kB)
Collecting executing>=1.2.0 (from stack-data->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for executing>=1.2.0 from https://files.pythonhosted.org/packages/80/03/6ea8b1b2a5ab40a7a60dc464d3daa7aa546e0a74d74a9f8ff551ea7905db/executing-2.0.1-py2.py3-none-any.whl.metadata
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Obtaining dependency information for asttokens>=2.1.0 from https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233b24a/asttokens-2.4.1-py2.py3-none-any.whl.metadata
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 4))
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Using cached jupyter_client-8.6.0-py3-none-any.whl (105 kB)
Using cached ipykernel-6.27.1-py3-none-any.whl (114 kB)
Using cached comm-0.2.0-py3-none-any.whl (7.0 kB)
Using cached debugpy-1.8.0-py2.py3-none-any.whl (5.0 MB)
Using cached ipython-8.18.1-py3-none-any.whl (808 kB)
Using cached jupyter_core-5.5.0-py3-none-any.whl (28 kB)
Using cached nbclient-0.9.0-py3-none-any.whl (24 kB)
Using cached nbformat-5.9.2-py3-none-any.whl (77 kB)
Using cached pyzmq-25.1.1-cp312-cp312-macosx_10_15_universal2.whl (1.9 MB)
Using cached tornado-6.4-cp38-abi3-macosx_10_9_universal2.whl (433 kB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Using cached traitlets-5.14.0-py3-none-any.whl (85 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl (246 kB)
Using cached PyYAML-6.0.1-cp312-cp312-macosx_11_0_arm64.whl (165 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl (119 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached jsonschema-4.20.0-py3-none-any.whl (84 kB)
Using cached pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
Using cached platformdirs-4.0.0-py3-none-any.whl (17 kB)
Using cached prompt_toolkit-3.0.41-py3-none-any.whl (385 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Using cached fastjsonschema-2.19.0-py3-none-any.whl (23 kB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Using cached jsonschema_specifications-2023.11.2-py3-none-any.whl (17 kB)
Using cached referencing-0.31.1-py3-none-any.whl (25 kB)
Using cached rpds_py-0.13.2-cp312-cp312-macosx_11_0_arm64.whl (325 kB)
Using cached wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
Installing collected packages: wcwidth, textwrap3, pure-eval, ptyprocess, find_libpython, fastjsonschema, appnope, urllib3, traitlets, tqdm, tornado, tenacity, six, rpds-py, pyzmq, pyyaml, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, packaging, nest-asyncio, idna, executing, entrypoints, decorator, debugpy, click, charset-normalizer, certifi, attrs, ansiwrap, requests, referencing, python-dateutil, matplotlib-inline, jupyter-core, jedi, comm, asttokens, stack-data, jupyter_client, jsonschema-specifications, jsonschema, ipython, nbformat, ipykernel, nbclient, papermill
Successfully installed ansiwrap-0.8.4 appnope-0.1.3 asttokens-2.4.1 attrs-23.1.0 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 comm-0.2.0 debugpy-1.8.0 decorator-5.1.1 entrypoints-0.4 executing-2.0.1 fastjsonschema-2.19.0 find_libpython-0.3.0 idna-3.6 ipykernel-6.27.1 ipython-8.18.1 jedi-0.19.1 jsonschema-4.20.0 jsonschema-specifications-2023.11.2 jupyter-core-5.5.0 jupyter_client-8.6.0 matplotlib-inline-0.1.6 nbclient-0.9.0 nbformat-5.9.2 nest-asyncio-1.5.8 packaging-23.2 papermill-2.4.0 parso-0.8.3 pexpect-4.9.0 platformdirs-4.0.0 prompt-toolkit-3.0.41 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.17.2 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.31.1 requests-2.31.0 rpds-py-0.13.2 six-1.16.0 stack-data-0.6.3 tenacity-8.2.3 textwrap3-0.9.2 tornado-6.4 tqdm-4.66.1 traitlets-5.14.0 urllib3-2.1.0 wcwidth-0.2.12

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/Users/macbook/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 29, in <module>
    import papermill as pm
  File "/Users/macbook/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/__init__.py", line 3, in <module>
    from .exceptions import PapermillException, PapermillExecutionError
  File "/Users/macbook/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/exceptions.py", line 3, in <module>
    from ansiwrap import strip_color
  File "/Users/macbook/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/macbook/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/core.py", line 6, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
modular: error: failed to run python:

~/Downloads/HD/coding/helloworld-mojo 1m 8s

```

### Steps to reproduce

- `modular install mojo`

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)

- What OS did you install modular CLI on ?
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
Model Name: MacBook Pro
      Model Identifier: MacBookPro17,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 8422.100.650
```

**Comment by Sharktheone** [comment] 2023-12-04 08:39
I think, this is tracked as #1102

**Comment by FomalhautWeisszwerg** [comment] 2023-12-04 08:50
This error is caused by `ansiwrap`, which `papermill` 2.4.0 depends on.

papermill 2.5 has remove use of ansiwrap, so this problem does not occur.
mojo should bump-up papermill to >=2.5.0.

**Comment by smuniraj2018** [comment] 2023-12-05 19:44
This should be fixed with the latest mojo release. Please give it a try after you update `modular update mojo` and let us know how it goes.

**Closed as completed** 2023-12-05 21:43 UTC
Labels: mojo, mojo-repo
